name: Build Astro Site

# Trigger the workflow on push to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Set permissions for GITHUB_TOKEN
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # Install dependencies
    - name: Install dependencies
      run: npm ci
      
    # Build the Astro project
    - name: Build Astro site
      run: npm run build
      
    # Commit the built files back to the repository
    - name: Commit built files
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local --add safe.directory /github/workspace
        git add publish/ || true
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Build: Update generated files [skip ci]" || true
          git push origin main || true
        fi